site_name: Burgonet Gateway Documentation

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - User Guide:
    - Use Cases: use-cases.md
    - Configuration: configuration.md
    - API Reference: api-reference.md
    - Chat Interface: chat-interface.md
  - Technical Documentation:
    - Architecture: technical.md
    - Features: features.md
  - Administration:
    - Monitoring: monitoring.md
  - About: about.md

theme:
  name: readthedocs
  features:
    - navigation.tabs
    - navigation.indexes
  palette:
    - scheme: default
      primary: indigo
      accent: blue
    - scheme: slate
      primary: blue
      accent: blue
  analytics:
    gtag: GTM-TSWFRGBR

plugins:
  - search
  - mermaid2
  - git-revision-date-localized

markdown_extensions:
  - admonition
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.tasklist

